const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const origin=process.env.PREVIEW_URL||'http://127.0.0.1:8090',out=path.join(__dirname,'verification/v6');fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge'}),passed=[];const record=n=>{passed.push(n);console.log(n);};
async function open(options={},query=''){const p=await b.newPage(options),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/'+query);await p.waitForFunction(()=>document.querySelector('.canvas').dataset.fontsReady==='true');await p.evaluate(()=>Promise.all([...document.images].map(i=>i.decode().catch(()=>{}))));return{p,errors};}
const playing=p=>p.waitForFunction(()=>document.querySelector('.character-layer[data-character=perlica]').dataset.videoState==='playing');
try{
 for(const width of [320,360,390,768,899,900,1366,1920]){
 const{p,errors}=await open({viewport:{width,height:1080},reducedMotion:'reduce'});
 const s=await p.evaluate(()=>{const q=s=>document.querySelector(s),d=q('.day-badge').getBoundingClientRect(),c=q('.number-corners').getBoundingClientRect();return{mobile:q('.canvas').classList.contains('mobile'),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,number:q('.number text').textContent,imgs:[...document.images].every(i=>i.complete&&i.naturalWidth>0),fonts:[...document.fonts].every(f=>f.status==='loaded'),center:Math.abs((d.top+d.bottom-c.top-c.bottom)/2),fits:q('.notice').offsetTop+q('.notice').offsetHeight<=q('.canvas').offsetHeight};});
 assert.equal(s.mobile,width<900);assert.equal(s.overflow,false);assert.equal(s.number,'039');assert(s.imgs&&s.fonts&&s.fits&&s.center<.1);assert.equal(await p.locator('video').count(),0);assert.deepEqual(errors,[]);await p.close();record('layout '+width+': breakpoint, fonts, DAY center, leading zero, no overflow');}
 for(const view of ['mobile','tv'])for(const character of ['perlica','amiya']){
 const{p,errors}=await open({viewport:view==='tv'?{width:1920,height:1080}:{width:360,height:703},deviceScaleFactor:view==='tv'?1:2},`?view=${view}&character=${character}&motion=off`);
 assert.equal(await p.locator('.canvas').evaluate(e=>e.classList.contains('mobile')),view==='mobile');assert.equal(await p.locator('video').count(),0);
 if(character==='amiya'){assert.equal(await p.locator('.amiya-scene').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');assert((await p.locator('.amiya-scene').evaluate(e=>getComputedStyle(e).maskImage)).includes('linear-gradient'));assert.equal(await p.locator('.amiya-scene img').evaluate(e=>getComputedStyle(e).opacity),'0.27');}
 await p.screenshot({path:path.join(out,`${view==='tv'?'desktop':'mobile'}-${character}.png`),fullPage:true});assert.deepEqual(errors,[]);await p.close();record(view+' '+character+': V6 static screenshot');}
 {
 const p=await b.newPage({viewport:{width:360,height:640},reducedMotion:'reduce'});await p.route('**/content.js*',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace("day:'1',number:'039'","day:'12',number:'0009'").replace("noticeMain:'請於叫號前返回 GRYPHLINE STORE 等候'","noticeMain:'請於叫號前返回 GRYPHLINE STORE 等候。現場人潮較多時請依工作人員引導，保持通道暢通並備妥入場憑證。'")});});await p.goto(origin);await p.waitForFunction(()=>document.querySelector('.canvas').dataset.fontsReady==='true');assert.equal(await p.locator('.number text').textContent(),'0009');assert.equal(await p.locator('.day-value text').textContent(),'12');assert(await p.evaluate(()=>document.querySelector('.notice').offsetTop+document.querySelector('.notice').offsetHeight<=document.querySelector('.canvas').offsetHeight));await p.close();record('DAY12, 0009 and long notice');}
 {
 const{p,errors}=await open({viewport:{width:1920,height:1080}});await playing(p);await p.waitForFunction(()=>+document.querySelector('.character-layer[data-character=perlica]').dataset.frames>10);
 await p.waitForFunction(()=>document.querySelector('.canvas').dataset.character==='amiya',{},{timeout:16000});await p.waitForTimeout(1100);assert.equal(await p.locator('video').count(),1);assert(await p.locator('video').evaluate(v=>v.paused));const transform=await p.locator('.amiya-scene img').evaluate(e=>getComputedStyle(e).transform);await p.waitForTimeout(1500);assert.notEqual(await p.locator('.amiya-scene img').evaluate(e=>getComputedStyle(e).transform),transform);
 await p.waitForFunction(()=>document.querySelector('.canvas').dataset.character==='perlica',{},{timeout:16000});await playing(p);assert.deepEqual(errors,[]);await p.close();record('full rotation: Perlica playback, Amiya drift, single paused decoder, return playback');}
 {
 const{p,errors}=await open({viewport:{width:390,height:844},isMobile:true,hasTouch:true},'?character=perlica');await playing(p);assert(await p.locator('.canvas').evaluate(e=>e.classList.contains('mobile')));assert((await p.locator('video').evaluate(v=>v.currentSrc)).endsWith('perlica-mobile.mp4'));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),false);await p.screenshot({path:path.join(out,'mobile-perlica-playing.png'),fullPage:true});
 await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});assert(await p.locator('video').evaluate(v=>v.paused));await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});await playing(p);
 await p.emulateMedia({reducedMotion:'reduce'});await p.waitForFunction(()=>document.querySelector('video').paused&&!document.querySelector('.has-video'));assert.deepEqual(errors,[]);await p.close();record('touch viewport: mobile media, simulated visibility resume, runtime reduced motion');}
 {
 const p=await b.newPage({viewport:{width:360,height:703}});await p.route('**/*.mp4',r=>r.abort());await p.goto(origin+'/?character=perlica');await p.waitForFunction(()=>document.querySelector('.character-layer[data-character=perlica]').dataset.videoState==='fallback');assert.equal(await p.locator('.has-video').count(),0);assert(await p.locator('.character-layer[data-character=perlica] img').evaluate(e=>e.complete&&e.naturalWidth>0));await p.close();record('missing video: one retry then visible poster');}
 {
 const p=await b.newPage({viewport:{width:360,height:703}});await p.route('**/amiya*.png',r=>r.abort());await p.goto(origin);await p.waitForTimeout(13500);assert.equal(await p.locator('.canvas').getAttribute('data-character'),'perlica');await p.close();record('missing Amiya artwork: keep complete Perlica scene');}
}finally{fs.writeFileSync(path.join(out,'site-results.json'),JSON.stringify({testedAt:new Date().toISOString(),origin,engine:'Windows Edge; touch and visibility simulation, no physical phone',passed},null,2));await b.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});

