const{chromium}=require('playwright'),assert=require('assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({channel:'msedge'});const results=[];
async function run(name,setup,options={}){const c=await b.newContext({viewport:{width:options.mobile?390:1280,height:844},isMobile:!!options.mobile,hasTouch:!!options.mobile});const p=await c.newPage();let errors=[];p.on('pageerror',e=>errors.push(e.message));try{await setup(p,c);assert.deepEqual(errors,[]);console.log(name+' passed');results.push({name,pass:true,state:await p.locator('.character-layer').evaluate(e=>({...e.dataset}))});}finally{await c.close();}}
const url='http://127.0.0.1:8090/verification/player-harness.html';
const playing=async p=>p.waitForFunction(()=>document.querySelector('.character-layer').dataset.videoState==='playing');
try{
for(const mobile of [false,true])await run(mobile?'mobile cold playback':'desktop cold playback',async p=>{await p.goto(url);await playing(p);const first=await p.locator('canvas').screenshot();await p.waitForTimeout(550);const second=await p.locator('canvas').screenshot();assert(!first.equals(second),'Rendered character pixels must change');const a=await p.locator('.character-layer').evaluate(e=>+e.dataset.frames);await p.waitForTimeout(7000);assert((await p.locator('.character-layer').evaluate(e=>+e.dataset.frames))>a+50);assert.equal(await p.locator('video').evaluate(v=>v.paused),false);await p.screenshot({path:__dirname+'/v6/player-'+(mobile?'mobile':'desktop')+'.png'});},{mobile});
await run('slow cold network',async(p,c)=>{const cdp=await c.newCDPSession(p);await cdp.send('Network.enable');await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:300,downloadThroughput:90000,uploadThroughput:40000});await p.goto(url);await playing(p);});
await run('autoplay denied',async p=>{await p.addInitScript(()=>HTMLMediaElement.prototype.play=function(){return Promise.reject(new DOMException('test','NotAllowedError'));});await p.goto(url);await p.waitForFunction(()=>document.querySelector('.character-layer').dataset.videoState==='fallback');assert.equal(await p.locator('.has-video').count(),0);});
await run('missing media bounded retry',async p=>{await p.route('**/*.mp4',r=>r.abort());await p.goto(url);await p.waitForFunction(()=>document.querySelector('.character-layer').dataset.videoState==='fallback');assert.equal(await p.locator('.character-layer').getAttribute('data-retries'),'1');});
await run('pending first frame timeout',async p=>{await p.addInitScript(()=>HTMLMediaElement.prototype.play=function(){return new Promise(()=>{});});await p.goto(url);await p.waitForFunction(()=>document.querySelector('.character-layer').dataset.videoState==='fallback',{},{timeout:25000});assert.equal(await p.locator('.character-layer').getAttribute('data-video-reason'),'first-frame-timeout');});
await run('stalled decoder recovery then fallback',async p=>{await p.goto(url);await playing(p);await p.evaluate(()=>{document.querySelector('video').pause();HTMLMediaElement.prototype.play=function(){return Promise.resolve();};});await p.waitForFunction(()=>document.querySelector('.character-layer').dataset.videoState==='fallback',{},{timeout:25000});assert.equal(await p.locator('.has-video').count(),0);});
await run('WebGL unavailable poster',async p=>{await p.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(t,...args){return t==='webgl'?null:get.call(this,t,...args);};});await p.goto(url);assert.equal(await p.locator('.character-layer').getAttribute('data-video-state'),'fallback');});
await run('context lost poster',async p=>{await p.goto(url);await playing(p);await p.evaluate(()=>document.querySelector('canvas').getContext('webgl').getExtension('WEBGL_lose_context').loseContext());await p.waitForFunction(()=>document.querySelector('.character-layer').dataset.videoState==='fallback');assert.equal(await p.locator('.has-video').count(),0);});
await run('resume and 60 second loops',async p=>{await p.goto(url);await playing(p);await p.evaluate(()=>player.stop());assert.equal(await p.locator('video').evaluate(v=>v.paused),true);await p.evaluate(()=>player.start());await playing(p);const first=await p.locator('canvas').screenshot();await p.waitForTimeout(550);const second=await p.locator('canvas').screenshot();assert(!first.equals(second),'Rendered character pixels must change');const a=await p.locator('.character-layer').evaluate(e=>+e.dataset.frames);await p.waitForTimeout(60000);assert((await p.locator('.character-layer').evaluate(e=>+e.dataset.frames))>a+500);});
}finally{fs.writeFileSync(__dirname+'/v6/player-results.json',JSON.stringify({date:new Date().toISOString(),engine:'Windows Edge Chromium; touch emulation is not physical mobile',results},null,2));console.log(JSON.stringify(results,null,2));await b.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});

