const{chromium}=require('playwright'),assert=require('assert/strict'),fs=require('fs'),path=require('path');
const origin=process.env.PREVIEW_URL||'http://127.0.0.1:8090',out=path.join(__dirname,'hq');fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({channel:'msedge'}),results=[];try{
for(const mobile of [false,true]){
 const p=await b.newPage({viewport:{width:mobile?390:1920,height:mobile?844:1080},isMobile:mobile,hasTouch:mobile});await p.goto(origin+'/?character=perlica');await p.waitForFunction(()=>document.querySelector('.has-video'));
 const sample=()=>p.evaluate(()=>{const l=document.querySelector('.character-layer[data-character=perlica]'),v=l.querySelector('video'),c=l.querySelector('canvas'),q=v.getVideoPlaybackQuality();return{source:v.currentSrc,frames:+l.dataset.frames,time:v.currentTime,firstFrameMs:+l.dataset.firstFrameMs,canvas:[c.width,c.height],video:[v.videoWidth,v.videoHeight],decoded:q.totalVideoFrames,dropped:q.droppedVideoFrames,state:l.dataset.videoState};});
 const before=await sample();await p.waitForTimeout(2100);const after=await sample();assert(after.source.endsWith(`perlica-${mobile?'mobile':'desktop'}-hq.mp4`));assert.deepEqual(after.canvas,mobile?[960,540]:[1440,810]);assert.deepEqual(after.video,mobile?[1920,540]:[2880,810]);assert(after.frames-before.frames>40);assert(after.decoded-before.decoded>40);assert.equal(after.state,'playing');results.push({name:mobile?'mobile HQ':'desktop HQ',before,after});await p.screenshot({path:path.join(out,mobile?'mobile-hq.png':'desktop-hq.png'),fullPage:true});await p.close();
}
const p=await b.newPage();await p.route('**/*-hq.mp4',r=>r.abort());await p.goto(origin+'/?character=perlica');await p.waitForFunction(()=>document.querySelector('.has-video'));const s=await p.evaluate(()=>({state:document.querySelector('.character-layer[data-character=perlica]').dataset.videoState,retries:document.querySelector('.character-layer[data-character=perlica]').dataset.retries,source:document.querySelector('video').currentSrc}));assert.equal(s.state,'playing');assert.equal(s.retries,'1');assert(s.source.endsWith('perlica-mobile.mp4'));results.push({name:'HQ failure recovers with lightweight video',...s});await p.close();
}finally{fs.writeFileSync(path.join(out,origin.startsWith('http://127.')?'local-results.json':'online-results.json'),JSON.stringify({date:new Date().toISOString(),origin,engine:'Windows Edge, touch simulation; not physical mobile',results},null,2));console.log(JSON.stringify(results,null,2));await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
